"""add tags to holding_transactions, net_worth_snapshots date indexes

Hand-written, not autogenerated: autogenerate diffs against the live schema
(created by raw SQL in supabase/migrations/) and proposes dropping check
constraints, unique constraints, and the assets_legacy backup table that
aren't modeled in models.py (see the baseline migration's docstring). This
migration only performs the two additive changes actually intended.

Revision ID: ef84aafcd23c
Revises: fe2ac0614b34
Create Date: 2026-08-13 16:55:17.045346

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ef84aafcd23c'
down_revision = 'fe2ac0614b34'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column(
        'holding_transactions',
        sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.create_index(
        'net_worth_snapshots_user_date_idx',
        'net_worth_snapshots',
        ['user_id', 'snapshot_date'],
    )
    op.create_index(
        'net_worth_snapshots_household_date_idx',
        'net_worth_snapshots',
        ['household_id', 'snapshot_date'],
    )


def downgrade():
    op.drop_index('net_worth_snapshots_household_date_idx', table_name='net_worth_snapshots')
    op.drop_index('net_worth_snapshots_user_date_idx', table_name='net_worth_snapshots')
    op.drop_column('holding_transactions', 'tags')
