-- Net Worth Tracker — initial Supabase schema
-- Run this once in the Supabase SQL Editor (or via `supabase db push`) against a fresh project.
--
-- Design notes:
-- * auth.users (Supabase Auth) is the source of truth for users — no local users table.
-- * Flask connects to this database with the service_role key (bypasses RLS) and enforces
--   authorization itself using the verified JWT's user_id. RLS below is enabled as
--   defense-in-depth for any client that connects as `authenticated` (e.g. a future
--   direct Supabase-client integration), not the primary authorization mechanism today.
-- * Household sharing is full co-edit: assets.household_id set = any member can read/write it.
--   assets.household_id null = private, owner-only.

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- households
-- ---------------------------------------------------------------------------
create table public.households (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  owner_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table public.household_members (
  household_id uuid not null references public.households(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'member' check (role in ('owner', 'member')),
  joined_at timestamptz not null default now(),
  primary key (household_id, user_id)
);

create index household_members_user_id_idx on public.household_members(user_id);

-- Every household owner is automatically a member too, so RLS checks that key off
-- household_members (assets, snapshots, etc.) include the owner without the app
-- having to remember to insert both rows.
create or replace function public.add_owner_as_member()
returns trigger as $$
begin
  insert into public.household_members (household_id, user_id, role)
  values (new.id, new.owner_id, 'owner')
  on conflict (household_id, user_id) do nothing;
  return new;
end;
$$ language plpgsql security definer set search_path = public;

create trigger households_add_owner_as_member
  after insert on public.households
  for each row
  execute function public.add_owner_as_member();

create table public.household_invites (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references public.households(id) on delete cascade,
  invited_email text not null,
  invited_by uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'revoked')),
  created_at timestamptz not null default now()
);

create index household_invites_email_idx on public.household_invites(invited_email);
create index household_invites_household_id_idx on public.household_invites(household_id);

-- ---------------------------------------------------------------------------
-- assets (migrated from the old SQLite `assets` table, extended with ownership)
-- ---------------------------------------------------------------------------
create table public.assets (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  household_id uuid references public.households(id) on delete set null,

  asset_type text not null check (
    asset_type in ('stock', 'mutual_fund', 'real_estate', 'metal', 'cash', 'deposit', 'loan')
  ),
  country text not null,
  account text not null,
  purchase_date date not null,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  -- market assets (stocks, mutual funds)
  symbol text,
  units double precision,
  buy_price double precision,

  -- real assets (real estate, metals)
  name text,
  buy_value double precision,
  current_value double precision,

  -- cash / deposits / loans
  institution text,
  value double precision,

  notes text,
  tags text
);

create index assets_user_id_idx on public.assets(user_id);
create index assets_household_id_idx on public.assets(household_id);

create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger assets_set_updated_at
  before update on public.assets
  for each row
  execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- net_worth_snapshots — one row per user per day, and one row per household per day
-- ---------------------------------------------------------------------------
create table public.net_worth_snapshots (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  household_id uuid references public.households(id) on delete cascade,
  snapshot_date date not null,
  total_net_worth double precision not null,
  total_stock_value double precision not null default 0,
  total_property_value double precision not null default 0,
  total_profit_loss double precision not null default 0,
  by_asset_type jsonb not null default '{}'::jsonb,
  currency text not null default 'USD',
  created_at timestamptz not null default now(),
  constraint snapshot_scope_check check (
    (user_id is not null and household_id is null) or
    (user_id is null and household_id is not null)
  )
);

-- Partial unique indexes: NULL columns don't collide under a plain UNIQUE constraint,
-- so we need separate indexes for the "individual" and "household" snapshot rows.
create unique index snapshot_unique_user
  on public.net_worth_snapshots(user_id, snapshot_date)
  where user_id is not null;

create unique index snapshot_unique_household
  on public.net_worth_snapshots(household_id, snapshot_date)
  where household_id is not null;

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------
alter table public.households enable row level security;
alter table public.household_members enable row level security;
alter table public.household_invites enable row level security;
alter table public.assets enable row level security;
alter table public.net_worth_snapshots enable row level security;

-- households: any member (including the owner, who is also a member row) can see it;
-- only the owner can rename/delete it.
create policy households_select on public.households
  for select using (
    owner_id = auth.uid()
    or id in (select household_id from public.household_members where user_id = auth.uid())
  );

create policy households_insert on public.households
  for insert with check (owner_id = auth.uid());

create policy households_update on public.households
  for update using (owner_id = auth.uid());

create policy households_delete on public.households
  for delete using (owner_id = auth.uid());

-- household_members: members can see who else is in their households.
-- No direct INSERT/UPDATE/DELETE policy for `authenticated` — membership changes
-- (accepting an invite, removing a member) go through the Flask backend using the
-- service_role key, which bypasses RLS entirely and enforces the invite/ownership logic.
create policy household_members_select on public.household_members
  for select using (
    user_id = auth.uid()
    or household_id in (select household_id from public.household_members where user_id = auth.uid())
  );

-- household_invites: the inviter and the invited person (by email) can see the invite.
create policy household_invites_select on public.household_invites
  for select using (
    invited_by = auth.uid()
    or invited_email = (auth.jwt() ->> 'email')
  );

-- assets: full co-edit within a shared household; private otherwise.
create policy assets_select on public.assets
  for select using (
    user_id = auth.uid()
    or household_id in (select household_id from public.household_members where user_id = auth.uid())
  );

create policy assets_insert on public.assets
  for insert with check (
    user_id = auth.uid()
    and (
      household_id is null
      or household_id in (select household_id from public.household_members where user_id = auth.uid())
    )
  );

create policy assets_update on public.assets
  for update using (
    user_id = auth.uid()
    or household_id in (select household_id from public.household_members where user_id = auth.uid())
  );

create policy assets_delete on public.assets
  for delete using (
    user_id = auth.uid()
    or household_id in (select household_id from public.household_members where user_id = auth.uid())
  );

-- net_worth_snapshots: read-only for the owning user/household. No INSERT/UPDATE policy
-- for `authenticated` at all — only the backend's service_role (which bypasses RLS) can
-- write snapshots, so users can't fabricate their own history.
create policy snapshots_select on public.net_worth_snapshots
  for select using (
    user_id = auth.uid()
    or household_id in (select household_id from public.household_members where user_id = auth.uid())
  );
