-- Net Worth Tracker — transaction-based holdings expansion
-- Additive: the existing `assets` table is untouched here. A separate backfill
-- script (backend/scripts/backfill_holdings.py) migrates its rows into the new
-- tables, then renames it to assets_legacy once verified. Nothing is dropped.

-- ---------------------------------------------------------------------------
-- Household roles: owner/member -> owner/editor/viewer
-- ---------------------------------------------------------------------------
alter table public.household_members drop constraint household_members_role_check;
update public.household_members set role = 'editor' where role = 'member';
alter table public.household_members
  add constraint household_members_role_check check (role in ('owner', 'editor', 'viewer'));
alter table public.household_members alter column role set default 'editor';

-- ---------------------------------------------------------------------------
-- holdings — one row per logical position (replaces the role of `assets`)
-- ---------------------------------------------------------------------------
create table public.holdings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  household_id uuid references public.households(id) on delete set null,

  asset_type text not null check (asset_type in (
    'stock', 'mutual_fund', 'crypto', 'commodity',
    'real_estate', 'fixed_deposit', 'ppf', 'epf', 'cash', 'loan'
  )),
  symbol text,              -- ticker / scheme code / coingecko id / metal code; null for non-tradeable types
  name text not null,       -- display name
  country text not null,
  account text not null,
  institution text,
  currency text not null,   -- native currency this holding is denominated in

  -- fixed_deposit / ppf / epf only
  interest_rate double precision,
  maturity_date date,

  is_private boolean not null default false,  -- hide from household aggregate even when shared
  notes text,
  tags text,
  status text not null default 'active' check (status in ('active', 'closed')),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index holdings_user_id_idx on public.holdings(user_id);
create index holdings_household_id_idx on public.holdings(household_id);
create index holdings_asset_type_idx on public.holdings(asset_type);

create trigger holdings_set_updated_at
  before update on public.holdings
  for each row
  execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- holding_transactions — buy/sell ledger for quantity-based holdings
-- ---------------------------------------------------------------------------
create table public.holding_transactions (
  id bigint generated by default as identity primary key,
  holding_id bigint not null references public.holdings(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  transaction_type text not null check (transaction_type in ('buy', 'sell')),
  transaction_date date not null,
  quantity double precision not null check (quantity > 0),
  price_per_unit double precision not null check (price_per_unit >= 0),
  currency text not null,
  fees double precision not null default 0,
  notes text,
  created_at timestamptz not null default now()
);

create index holding_transactions_holding_id_idx on public.holding_transactions(holding_id);
create index holding_transactions_user_id_idx on public.holding_transactions(user_id);
create index holding_transactions_date_idx on public.holding_transactions(transaction_date);

-- ---------------------------------------------------------------------------
-- holding_valuations — periodic value/balance entries for non-tradeable holdings
-- ---------------------------------------------------------------------------
create table public.holding_valuations (
  id bigint generated by default as identity primary key,
  holding_id bigint not null references public.holdings(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  valuation_date date not null,
  value double precision not null,
  currency text not null,
  notes text,
  created_at timestamptz not null default now()
);

create index holding_valuations_holding_id_idx on public.holding_valuations(holding_id);
create index holding_valuations_user_id_idx on public.holding_valuations(user_id);
create index holding_valuations_date_idx on public.holding_valuations(valuation_date);

-- ---------------------------------------------------------------------------
-- price_history — cached prices, global (not user-scoped, no RLS needed)
-- ---------------------------------------------------------------------------
create table public.price_history (
  id bigint generated by default as identity primary key,
  asset_type text not null,
  symbol text not null,
  price_date date not null,
  price double precision not null,
  currency text not null,
  source text,
  created_at timestamptz not null default now(),
  unique (asset_type, symbol, price_date)
);

create index price_history_lookup_idx on public.price_history(asset_type, symbol, price_date desc);

-- ---------------------------------------------------------------------------
-- exchange_rates — cached FX rates, global (not user-scoped, no RLS needed)
-- ---------------------------------------------------------------------------
create table public.exchange_rates (
  id bigint generated by default as identity primary key,
  base_currency text not null,
  quote_currency text not null,
  rate_date date not null,
  rate double precision not null,
  created_at timestamptz not null default now(),
  unique (base_currency, quote_currency, rate_date)
);

create index exchange_rates_lookup_idx on public.exchange_rates(base_currency, quote_currency, rate_date desc);

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------
alter table public.holdings enable row level security;
alter table public.holding_transactions enable row level security;
alter table public.holding_valuations enable row level security;

-- holdings: own rows always visible; shared household rows visible to members
-- unless flagged private. Writes require owner/editor role in that household.
create policy holdings_select on public.holdings
  for select using (
    user_id = auth.uid()
    or (
      is_private = false
      and household_id in (select household_id from public.household_members where user_id = auth.uid())
    )
  );

create policy holdings_insert on public.holdings
  for insert with check (
    user_id = auth.uid()
    and (
      household_id is null
      or household_id in (
        select household_id from public.household_members
        where user_id = auth.uid() and role in ('owner', 'editor')
      )
    )
  );

create policy holdings_update on public.holdings
  for update using (
    user_id = auth.uid()
    or household_id in (
      select household_id from public.household_members
      where user_id = auth.uid() and role in ('owner', 'editor')
    )
  );

create policy holdings_delete on public.holdings
  for delete using (
    user_id = auth.uid()
    or household_id in (
      select household_id from public.household_members
      where user_id = auth.uid() and role in ('owner', 'editor')
    )
  );

-- holding_transactions / holding_valuations: authorization follows the parent
-- holding (own, or an editor/owner of the household it's shared into).
create policy holding_transactions_select on public.holding_transactions
  for select using (
    user_id = auth.uid()
    or holding_id in (
      select id from public.holdings h
      where h.is_private = false
        and h.household_id in (select household_id from public.household_members where user_id = auth.uid())
    )
  );

create policy holding_transactions_write on public.holding_transactions
  for all using (
    user_id = auth.uid()
    or holding_id in (
      select id from public.holdings h
      where h.household_id in (
        select household_id from public.household_members
        where user_id = auth.uid() and role in ('owner', 'editor')
      )
    )
  );

create policy holding_valuations_select on public.holding_valuations
  for select using (
    user_id = auth.uid()
    or holding_id in (
      select id from public.holdings h
      where h.is_private = false
        and h.household_id in (select household_id from public.household_members where user_id = auth.uid())
    )
  );

create policy holding_valuations_write on public.holding_valuations
  for all using (
    user_id = auth.uid()
    or holding_id in (
      select id from public.holdings h
      where h.household_id in (
        select household_id from public.household_members
        where user_id = auth.uid() and role in ('owner', 'editor')
      )
    )
  );
