-- Price alerts and net worth milestones.

create table public.price_alerts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  holding_id bigint references public.holdings(id) on delete cascade,
  symbol text,
  asset_type text,
  alert_type text not null check (alert_type in ('price_above', 'price_below', 'net_worth_above', 'net_worth_below')),
  threshold double precision not null,
  currency text not null default 'USD',
  status text not null default 'active' check (status in ('active', 'triggered', 'cancelled')),
  created_at timestamptz not null default now(),
  triggered_at timestamptz
);

create index price_alerts_user_id_idx on public.price_alerts(user_id);
create index price_alerts_status_idx on public.price_alerts(status);

alter table public.price_alerts enable row level security;

create policy price_alerts_all on public.price_alerts
  for all using (user_id = auth.uid());

-- Milestones: one row per user or household per (threshold, currency) crossed.
create table public.milestones (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  household_id uuid references public.households(id) on delete cascade,
  threshold double precision not null,
  currency text not null,
  achieved_date date not null,
  acknowledged boolean not null default false,
  created_at timestamptz not null default now(),
  constraint milestone_scope_check check (
    (user_id is not null and household_id is null) or
    (user_id is null and household_id is not null)
  )
);

create unique index milestones_unique_user
  on public.milestones(user_id, threshold, currency)
  where user_id is not null;

create unique index milestones_unique_household
  on public.milestones(household_id, threshold, currency)
  where household_id is not null;

alter table public.milestones enable row level security;

-- Read-only for users; only the backend's service-role connection (which
-- bypasses RLS) inserts milestone rows, from the daily snapshot job.
create policy milestones_select on public.milestones
  for select using (
    user_id = auth.uid()
    or household_id in (select household_id from public.household_members where user_id = auth.uid())
  );
